src/main/java/ru/tn/managedBean/HeaderTemplateMBean.java
package ru.tn.managedBean;

import ru.tn.sessionBean.HeaderTemplateSBean;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import java.io.Serializable;
import java.security.Principal;

@ManagedBean(name = "headerTemplate")
@SessionScoped
public class HeaderTemplateMBean implements Serializable {

    @EJB
    private HeaderTemplateSBean bean;

    private String user;
    private String userPrincipal;

    public String logout() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
        return "/view/authentication/login.xhtml?faces-redirect=true";
    }

    public boolean isUserAllowedAccess() {
        return FacesContext.getCurrentInstance().getExternalContext().isUserInRole("ADMIN");
    }

    public String getUser() {
        if (user == null) {
            Principal principal = FacesContext.getCurrentInstance().getExternalContext().getUserPrincipal();
            if (principal != null) {
                userPrincipal = principal.getName();
                user = bean.getUserDescription(principal.getName());
            }
        }
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getUserPrincipal() {
        return userPrincipal;
    }

    public void setUserPrincipal(String userPrincipal) {
        this.userPrincipal = userPrincipal;
    }
}

src/main/webapp/view/template/contentTempl.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h3>Шаблон</h3>
</ui:composition>

src/main/webapp/view/template/footerTempl.xhtml
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <div style="text-align: center">Copyright © 2019 "ТЕКОН-Диспетчеризация"</div>
</ui:composition>

src/main/webapp/view/template/headerTempl.xhtml
<ui:composition xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    <h:form>
        <p:menubar>
            <p:submenu label="Оперативный контроль" icon="pi pi-home">
                <p:submenu label="Ведомость параметров">
                    <p:menuitem value="Ведомость технологических параметров"
                                icon="pi pi-table"
                                url="#{request.contextPath}/view/web/techDataSheet.xhtml"/>
                    <p:menuitem value="Многофункциональный отчет" url="#"/>
                </p:submenu>
                <p:separator/>
                <p:menuitem value="Контроль состояний" url="#"/>
                <p:menuitem value="Технологическая связь объектов" url="#"/>
                <p:menuitem value="Последние данные" url="#"/>
            </p:submenu>

            <p:menuitem value="Описание системы" icon="pi pi-file" url="#"/>

            <p:submenu label="Администрирование"
                       rendered="#{headerTemplate.userAllowedAccess}"
                       icon="pi pi-cog">
                <p:menuitem  value="Регистрация пользователей"/>
            </p:submenu>

            <f:facet name="options">
                <p:outputLabel style="margin: 1px 10px 1px 1px;" value="#{headerTemplate.user}"/>
                <p:commandButton value="Выход" icon="pi pi-sign-out" action="#{headerTemplate.logout}"/>
            </f:facet>
        </p:menubar>
    </h:form>
</ui:composition>

src/main/webapp/view/template/navigTempl.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:p="http://primefaces.org/ui">
    <p:panel id="navigPanel" header="Навигация" style="width: 100%; height: 100%;">

        <h:form id="navig" style="height: calc(100% - 43px)">
            <h:panelGrid columns="2" styleClass="fieldwrapper" columnClasses=",col">
                <p:outputLabel for="objType" value="Тип объекта:"/>
                <p:selectOneMenu id="objType" value="#{navigation.selectedObjType}" dynamic="true"
                                 style="width: 100%; margin-right: -100px;">
                    <f:selectItems value="#{navigation.objTypeList}" var="type"
                                   itemLabel="#{type.objTypeName}" itemValue="#{type.objTypeId}"/>

                    <p:ajax event="itemSelect" listener="#{navigation.changeObjTypeListener}"
                            update=":navig:search :navig:orgTree"/>
                </p:selectOneMenu>
            </h:panelGrid>

            <p:tree id="orgTree" widgetVar="orgTreeWidget" value="#{navigation.root}" var="node" dynamic="true"
                    selectionMode="single" selection="#{navigation.selectedNode}" cache="false"
                    styleClass="tree" style="width: 100%">
                <p:treeNode expandedIcon="pi pi-folder-open" collapsedIcon="pi pi-folder">
                    <h:outputText value="#{node.name}"/>
                </p:treeNode>

                <p:treeNode type="leaf" icon="pi pi-file">
                    <h:outputText value="#{node.name}"/>
                </p:treeNode>

                <p:ajax event="select" listener="#{navigation.onNodeSelect}"/>
                <p:ajax event="expand" listener="#{navigation.onNodeExpand}"/>
                <p:ajax event="collapse" listener="#{navigation.onNodeCollapse}"/>
            </p:tree>

            <h:panelGrid columns="2" styleClass="fieldwrapper" columnClasses=",col" style="margin-top: 3px">
                <p:outputLabel for="search" value="Тип поиска:"/>
                <p:selectOneMenu id="search" value="#{navigation.selectedSearch}" dynamic="true"
                                 style="width: 100%; margin-right: -100px;">
                    <f:selectItems value="#{navigation.searchList}" var="prop"
                                   itemLabel="#{prop.objTypeValue}" itemValue="#{prop.objTypeId}"/>
                </p:selectOneMenu>
            </h:panelGrid>
        </h:form>

        <h:form id="searchButton">
            <h:panelGrid columns="2" columnClasses="col" style="margin-top: 5px">
                <p:inputText  value="#{navigation.searchText}" style="width: 100%"/>
                <p:commandButton value="Перестроить" action="#{navigation.updateSearch()}"
                                 update=":navig:orgTree"/>
            </h:panelGrid>
        </h:form>

        <h:form id="action">
            #{bean[method](navigation.selectedNodeId)}
        </h:form>
    </p:panel>
</ui:composition>

src/main/webapp/view/template/portalTempl.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
    <h:outputStylesheet name="style.css" library="css"/>
    <script type="text/javascript" src="https://cdn.rawgit.com/lingtalfi/simpledrag/master/simpledrag.js"/>
    <h:outputScript name="script.js" library="js" target="body"/>
</h:head>
<h:body>
    <p:ajaxStatus style="width: 32px; height: 32px; position: fixed; right: 20px; bottom: 20px">
        <f:facet name="start">
            <i class="pi pi-spin pi-spinner" style="font-size: 3em"/>
        </f:facet>

        <f:facet name="complete">
            <h:outputText value="" />
        </f:facet>
    </p:ajaxStatus>

    <div id="page">
        <div class="top">
            <ui:insert name="header">
                <ui:include src="/view/template/headerTempl.xhtml"/>
            </ui:insert>
        </div>

        <div class="panes-container">
            <div class="left-pane" id="left-pane">
                <div class="box">
                    <ui:insert name="left-pane">
                        <ui:include src="/view/template/contentTempl.xhtml"/>
                    </ui:insert>
                </div>
            </div>

            <div class="panes-separator" id="panes-separator"/>

            <div class="right-pane" id="right-pane">
                <div class="box">
                    <ui:insert name="right-pane">
                        <ui:include src="/view/template/contentTempl.xhtml"/>
                    </ui:insert>
                </div>
            </div>
        </div>
    </div>
</h:body>
</html>